kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1

metadata: 
  name: online-shop-vpa
  namespace: online-shop

spec:
  tergetRef:
    apiVersion: apps/v1
    kind: Deployemt
    name: online-shop-deployment

  updatePolicy:
    updateMode: "Auto"
